backend:
  name: git-gateway
  branch: master

media_folder: "images/recipes"

collections:
  - name: "recipes"
    label: "Recipes"
    label_singular: "Recipe"
    folder: "site/recipes"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "imgcredit", label: "Photo Credit", widget: "string" }
      - { name: "source", label: "Recipe Source", widget: "string" }
      - { name: "sourcelink", label: "Source URL", widget: "string" }
      - {
          name: "image",
          label: "Image",
          widget: "image",
          allow_multiple: false,
        }
      - { name: "ingredients", label: "Ingredients", widget: "list" }
      - { name: "body", label: "Steps", widget: "markdown" }
      - { name: "searchterms", label: "Search Terms", widget: "list" }
